<?php


namespace SimplifiedMagento\VipDatabaseSchema\Model;

use Magento\Framework\Model\AbstractModel;
use \SimplifiedMagento\VipDatabaseSchema\Model\ResourceModel\VipMember as VipMemberResource;

class VipMember extends AbstractModel
{
    protected function _construct()
    {
        $this->_init(VipMemberResource::class);
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}