<?php


namespace SimplifiedMagento\Database\Model\ResourceModel\AffiliateMembers;


use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use SimplifiedMagento\Database\Model\AffiliateMembers;
use SimplifiedMagento\Database\Model\ResourceModel\AffiliateMembers as AffiliateMemberResource;

class Collection extends AbstractCollection
{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init(AffiliateMembers::class, AffiliateMemberResource::class);
    }
}