<?php


namespace SimplifiedMagento\Database\Model;


use Magento\Framework\Model\AbstractExtensibleModel;
use Magento\Framework\Model\AbstractModel;
use SimplifiedMagento\Database\Api\Data\AffiliateMembersExtensionInterface;
use SimplifiedMagento\Database\Model\ResourceModel\AffiliateMembers as AffiliateMembersResourse;
use SimplifiedMagento\Database\Api\Data\AffiliateMembersInterface;

class AffiliateMembers extends AbstractExtensibleModel implements AffiliateMembersInterface
{
    protected function _construct()
    {
        $this->_init(AffiliateMembersResourse::class);
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return int|mixed|void
     */
    public function getId()
    {
        return $this->getData(AffiliateMembersInterface::ID);
    }

        /**
     * @return string
     */
    public function getName()
    {
       return $this->getData(AffiliateMembersInterface::NAME);
    }

    /**
     * @return boolean
     */
    public function getStatus()
    {
        return $this->getData(AffiliateMembersInterface::STATUS);
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->getData(AffiliateMembersInterface::ADDRESS);
    }

    /**
     * @return int
     */
    public function getPhoneNumber()
    {
        return $this->getData(AffiliateMembersInterface::PHONE_NUMBER);
    }

    /**
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->getData(AffiliateMembersInterface::CREATED_AT);
    }

    /**
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->getData(AffiliateMembersInterface::UPDATED_AT);
    }

    /**
     * @param $name
     * @return \SimplifiedMagento\Database\Api\Data\AffiliateMembersInterface
     */
    public function setName($name)
    {
        $this->setData(AffiliateMembersInterface::NAME, $name);
    }

    /**
     * @param $status
     * @return \SimplifiedMagento\Database\Api\Data\AffiliateMembersInterface
     */
    public function setStatus($status)
    {
        $this->setData(AffiliateMembersInterface::STATUS, $status);
    }

    /**
     * @param $address
     * @return \SimplifiedMagento\Database\Api\Data\AffiliateMembersInterface
     */
    public function setAddress($address)
    {
        $this->setData(AffiliateMembersInterface::ADDRESS, $address);
    }

    /**
     * @param $phoneNumber
     * @return \SimplifiedMagento\Database\Api\Data\AffiliateMembersInterface
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->setData(AffiliateMembersInterface::PHONE_NUMBER, $phoneNumber);
    }

    /**
     * @return \SimplifiedMagento\Database\Api\Data\AffiliateMembersExtensionInterface|null
     */
    public function getExtensionAttributes()
    {
        return $this->getExtensionAttributes();
    }

    /**
     * @param AffiliateMembersExtensionInterface $affiliateMembersExtension
     * @return $this
     */
    public function setExtensionAttributes(\SimplifiedMagento\Database\Api\Data\AffiliateMembersExtensionInterface $affiliateMembersExtension)
    {
        return $this->setExtensionAttributes($affiliateMembersExtension);
    }
}